output: docs
author: gematik GmbH
author_url: http://www.gematik.de
exclude: /*/internal*
module: NFCCardReaderProvider
github_url: http://www.github.com/gematik/ref-CardReaderProvider-NFC-iOS.git
theme: jony
xcodebuild_arguments:
- "-project"
- 'NFCCardReaderProvider.xcodeproj'
